import { Playfair_Display } from "@next/font/google";
import "./globals.css";
import Head from "next/head";
import Header from "./Component/Header";
import Footer from "./Component/Footer";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"], 
  weight: ["400", "700"], 
});

export const metadata = {
  title: "Headless Cms",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css"
          rel="stylesheet"
        />
          <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>

      </Head>

      <body
        className={`${playfairDisplay.variable}`}
      >
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
